大二小学期项目/BUAAzhihu/BUAAzhihu/BUAAzhihu/urls.py
from django.contrib import admin
from django.urls import path
from app1.views import user, index
urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', user.login),
    path('register/', user.register),
    path('logout/', user.logout),
    path('<int:nid>/ask/raise', user.ask),
    path('<int:nid>/homepage', user.self_homepage),

    path('ask/delete', user.ask_delete),
    path('ans/delete', user.ans_delete),
    path('agree/delete', user.agree_delete),
    path('focus/delete', user.focus_delete),
    path('focus/delete', user.focus_delete),
    path('ask/edit', user.ask_edit),
    path('ask/edit/confirm', user.ask_edit_confirm),
    path('ans/edit', user.ans_edit),
    path('ans/edit/confirm', user.ans_edit_confirm),

    path('index/', index.show_homepage),
    path('problem/set', index.problem_set),
    path('<int:nid>/problem', index.problem_page),
    path('index/recommend/', index.index_recommend),
    path('<int:pid>/problem/<int:nid>/answer', index.answer_page),

    path('answer/agree/', index.answer_agree),
    path('answer/agree/cancel/', index.answer_agree_cancel),
    path('problem/follow/', index.problem_follow),
    path('problem/follow/cancel/', index.problem_follow_cancel),

]

大二小学期项目/BUAAzhihu/BUAAzhihu/app1/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.

class ask_list(models.Model):
    asker = models.ForeignKey(to="user_list", to_field="id", on_delete=models.CASCADE)
    title = models.CharField(verbose_name="问题题目", max_length=128)
    ask_intro = models.TextField(verbose_name="问题简介")
    ask_time = models.DateTimeField(auto_now_add=True)
    ask_choices = (
        (1, "学习"),
        (2, "生活"),
        (3, "吐槽"),
        (4, "选课")
    )   # 这是django中的约束
    ask_kind = models.SmallIntegerField(verbose_name="问题标签", choices=ask_choices, null=True, blank=True)
    def __str__(self):
        return self.title
        
class ans_list(models.Model):
    ans_content = models.TextField(verbose_name="回答文本")
    author = models.ForeignKey(to="user_list", to_field="id", on_delete=models.CASCADE)
    thisask = models.ForeignKey(to="ask_list", to_field="id", on_delete=models.CASCADE)
    ans_time = models.DateTimeField(auto_now_add=True)
    see_num = models.IntegerField(verbose_name="浏览量", default=0)
    def __str__(self):
        return self.ans_content[0:40]

class comment_list(models.Model):
    comment_content = models.CharField(verbose_name="评论", max_length=200)
    thiscomment = models.ForeignKey(to="ans_list", to_field="id", on_delete=models.CASCADE)
    commenter = models.ForeignKey(to="user_list", to_field="id", on_delete=models.CASCADE)  
    comment_time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content[0:40]

class user_list(models.Model):
    name = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    email = models.CharField(verbose_name="邮箱", max_length=64)
    intro = models.CharField(verbose_name="个人简介", max_length=200, null=True, blank=True)
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )   # 这是django中的约束
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)
    academy = (
        (2, "电子信息工程学院"),
        (6, "计算机学院"),
        (21, "软件学院"),
    )
    academy = models.SmallIntegerField(verbose_name="学院", choices=academy, default=21)
    vote_ans = models.ManyToManyField(ans_list, verbose_name="赞同回答", null=True, blank=True)
    focus_ask = models.ManyToManyField(ask_list, verbose_name="关注问题", null=True, blank=True)
    def __str__(self):
        return self.name

大二小学期项目/BUAAzhihu/BUAAzhihu/app1/views/index.py
from re import search
from urllib.request import HTTPRedirectHandler
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django import forms
from app1 import models
from django.views.decorators.csrf import csrf_exempt
import json
from app1.utils.pagination import Pagination

def show_homepage(request):

    # 检查用户是否已经登录
    info = request.session.get("info")
    if not info:
        return redirect('/login/')


    user_id = request.session['info']['id']
    user_object = models.user_list.objects.filter(id=user_id).first()
    agree_list = []
    data_dict = {}
    search_data = request.GET.get("q", "")
    if search_data:
        data_dict["ans_content__contains"] = search_data

    sort_kind = request.GET.get("sort", "")
    if sort_kind == "rec" or not sort_kind:
        answers = models.ans_list.objects.filter(**data_dict).order_by("?")
    elif sort_kind == "time":
        answers = models.ans_list.objects.filter(**data_dict).order_by("-ans_time")
    elif sort_kind == "hot":
        answers = models.ans_list.objects.filter(**data_dict).order_by("-see_num")
    
    tag_kind = request.GET.get("tag", "")
    if tag_kind == "xuexi":
        answers = models.ans_list.objects.filter(thisask__ask_kind=1).all()
    elif tag_kind == "shenghuo":
        answers = models.ans_list.objects.filter(thisask__ask_kind=2).all()
    elif tag_kind == "tucao":
        answers = models.ans_list.objects.filter(thisask__ask_kind=3).all()
    elif tag_kind == "xuanke":
        answers = models.ans_list.objects.filter(thisask__ask_kind=4).all()



    agree_answers = user_object.vote_ans.all()
    for answer in answers:
        if answer in agree_answers:
            agree_list.append(1)
        else:
            agree_list.append(0)

    # 列表存储每个回答的赞同数
    vote_ans_list = []
    for answer in answers:
        num = answer.user_list_set.all().count()
        vote_ans_list.append(num)

    page_object = Pagination(request, answers, page_size=10)
    return render(request, 'homepage.html', {"user_id": info['id'], "answers": page_object.page_queryset, 
                                            "search_data": search_data, "agree_list": agree_list,
                                            'page_string': page_object.html(), "vote_ans_list": vote_ans_list})


def problem_set(request):
    info = request.session.get("info")
    if not info:
        return redirect('/login/')


    data_dict = {}
    search_data = request.GET.get("q", "")
    if search_data:
        data_dict["title__contains"] = search_data

    problem_list = models.ask_list.objects.filter(**data_dict).order_by("-ask_time")

    tag_kind = request.GET.get("tag", "")
    if tag_kind == "xuexi":
        problem_list = models.ask_list.objects.filter(ask_kind=1).all()
    elif tag_kind == "shenghuo":
        problem_list = models.ask_list.objects.filter(ask_kind=2).all()
    elif tag_kind == "tucao":
        problem_list = models.ask_list.objects.filter(ask_kind=3).all()
    elif tag_kind == "xuanke":
        problem_list = models.ask_list.objects.filter(ask_kind=4).all()

    page_object = Pagination(request, problem_list, page_size=10)
    return render(request, 'problem_set.html', {"problems": page_object.page_queryset, "user_id": request.session['info']['id'], 
                                                "search_data": search_data, "page_string":page_object.html()})
    
def problem_page(request, nid):
    info = request.session.get("info")
    if not info:
        return redirect('/login/')


    problem_object = models.ask_list.objects.filter(id=nid).first()
    answers_object = models.ans_list.objects.filter(thisask=nid).all()
    answers_num = answers_object.count()
    followers = problem_object.user_list_set.all().count()
    author_id = request.session['info']['id']
    author_object = models.user_list.objects.filter(id=author_id).first()
    problems_focus = author_object.focus_ask.all()
    if problem_object in problems_focus:
        status = True;
    else: 
        status = False;
    problem_dict = {"problem": problem_object, 
                    "answers": answers_object, 
                    "followers": followers,
                    "answers_num": answers_num,
                    "focus_status": status,
                    }

    if request.method == 'GET':
        return render(request, 'problem_page.html', problem_dict)

    ans = request.POST.get("answer_sheet")
    
    have_answered = models.ans_list.objects.filter(author_id=author_id, thisask_id=nid).first() #每个用户对于一个问题只能答一次
    if not have_answered:
        models.ans_list.objects.create(ans_content=ans, author=author_object, thisask=problem_object)
    answers_object = models.ans_list.objects.filter(thisask=nid).all()
    answers_num = answers_object.count()
    problem_dict["answers_num"] = answers_num
    return render(request, 'problem_page.html',problem_dict)


def answer_page(request, pid, nid):

    info = request.session.get("info")
    if not info:
        return redirect('/login/')


    comment = request.POST.get("pinglun")
    commenter_id = request.session['info']['id']
    commenter = models.user_list.objects.filter(id=commenter_id).first()
    thisanswer = models.ans_list.objects.filter(id=nid).first()
    


    if request.method == 'GET':
        problem_object = models.ask_list.objects.filter(id=pid).first()
        vote_num = thisanswer.user_list_set.all().count()
        comment_objects = models.comment_list.objects.filter(thiscomment=thisanswer).all().order_by("-comment_time")
        comment_num = comment_objects.count()

        see_num = thisanswer.see_num
        see_num = see_num + 1
        models.ans_list.objects.filter(id=nid).update(see_num=see_num)

        if thisanswer in commenter.vote_ans.all():
            status = True
        else:
            status = False
        ans_dict = {
            "answer": thisanswer, 
            "problem": problem_object,
            "vote_num": vote_num,
            "comment_num": comment_num,
            "comments": comment_objects,
            "status": status,
            "user_id": commenter_id
        }
        return render(request, "answer_page.html", ans_dict)
    models.comment_list.objects.create(comment_content=comment, thiscomment=thisanswer, commenter=commenter)
    return redirect(f'/{pid}/problem/{nid}/answer')



@csrf_exempt
def answer_agree(request):
    answer_id = request.POST.get("answer_id")
    user_id = request.session['info']['id']
    user_object = models.user_list.objects.filter(id=user_id).first()
    answer_object = models.ans_list.objects.filter(id=answer_id).first()
    user_object.vote_ans.add(answer_object)

    data_dict = {'status': True}
    return HttpResponse(json.dumps(data_dict))

@csrf_exempt
def answer_agree_cancel(request):
    answer_id = request.POST.get("answer_id")
    user_id = request.session['info']['id']
    user_object = models.user_list.objects.filter(id=user_id).first()
    answer_object = models.ans_list.objects.filter(id=answer_id).first()
    user_object.vote_ans.remove(answer_object)
    data_dict = {'status': True}
    return HttpResponse(json.dumps(data_dict))


@csrf_exempt
def problem_follow(request):
    problem_id = request.POST.get("problem_id")
    problem_object = models.ask_list.objects.filter(id=problem_id).first()
    user_id = request.session['info']['id']
    user_object = models.user_list.objects.filter(id=user_id).first()
    user_object.focus_ask.add(problem_object)
    
    data_dict = {'status': True}
    return HttpResponse(json.dumps(data_dict))

@csrf_exempt
def problem_follow_cancel(request):
    problem_id = request.POST.get("problem_id")
    problem_object = models.ask_list.objects.filter(id=problem_id).first()
    user_id = request.session['info']['id']
    user_object = models.user_list.objects.filter(id=user_id).first()
    user_object.focus_ask.remove(problem_object)
    
    data_dict = {'status': True}
    return HttpResponse(json.dumps(data_dict))

@csrf_exempt
def index_recommend(request):
    print(request.POST)
    data_dict = {'status': True}
    return HttpResponse(json.dumps(data_dict))

大二小学期项目/BUAAzhihu/BUAAzhihu/app1/templates/answer_page.html
{% extends 'daohanglan.html' %}

{% block title %}
回答界面
{% endblock title %}

{% block style %}
.content_container{
    margin-left: auto;
    margin-right: auto;
    width: 1030px;
  }
  
  .fixed_mianban{
    position: fixed;
    right: 215px;
  }
  
  .question_card{
    background-color: white;
    width: 100%;
    padding-left: auto;
    padding-right: auto;
    margin-top: 0px;
  }
  .question_card a{
    text-decoration: none;
  }
  .username{
    display: inline-block;
    margin-top: 10px;
    margin-left: 5px;
  }
  .username_ans{
    text-align: center;
    margin-top: 10px;
  }
  .title_color{
    color: black;
  }
  .question_title{
    font-size:25px;
    font-weight: 600;
    margin-top: 10px;
    padding: 10px 10px 5px 10px;
  }
  
  .question_card .question_title a:hover{
    color: #625199;
  }
  
  .date{
    display: inline-block;
    margin-right: 10px;
  }
  .answer{
    font-size:15px;
    padding:  0px 10px;
  }
  .answer_color{
    color:black;
  }
  .question_card .answer a:hover{
    color: grey;
  }
  
  .product-buyer-name {
    overflow:hidden; 
    text-overflow:ellipsis;
    display:-webkit-box; 
    -webkit-box-orient:vertical;
    -webkit-line-clamp:2; 
  }
  
  .question_intro{
    font-size:15px;
    font-weight: 400;
    margin-top: 10px;
    padding: 10px 10px 5px 10px;
  }

  .agreebutton{
    display: inline-block;
    vertical-align: center;
    margin-left: 110px;
    margin-bottom: 10px;
  } 

  .comment_container{
    width: 500px;
    margin-left: auto;
    margin-right: auto;
  }
  .comment_card{
    margin-top: 25px;
    width: 100%;
    background-color: white;
  }
  .comment{
    padding: 20px 20px;
    height: 120px;
  }

  .col-md-3 a{
    text-decoration: none;
    font-size: 25px; 
    color: #238E68; 
    font-weight: bold
  }
  
  #tiwen:hover{
    color: #238000;
  }
  
  .col-md-3 button{
    background-color: #238E68;
    color: white;
    font-weight: bold;
  }
{% endblock style %}


{% block content %}
<div class="content_container">
    <div class="row">
      <div class="col-md-8" style="height: 1000px"> 

        <div class="question_card clearfix">
          <div class="col-md-12">
            <i class="fa fa-user-circle" aria-hidden="true" style="margin-left: 10px"></i>
            <div class="username">
              {{problem.asker}} 于
            </div>
            <div class="date">
              {{problem.ask_time|date:"Y-m-d"}} 提出
            </div>
            <div class="question_title">
              <a href="/{{problem.id}}/problem" style="color:black">{{problem.title}}</a>
            </div>
            <div class="question_intro">
              补充描述：<div style="color:black">{{problem.ask_intro}}</div>
            </div>
          </div>
        </div>
        <div>
          <div class="question_card clearfix" style="position:relative; margin-top:10px;">
            <div class="col-xs-2">
                <div><i class="fa fa-user-circle fa-5x" aria-hidden="true" style="margin-left: 10px; margin-top:10px; display:inline-block;"></i></div>
                <div class="username_ans" style="margin-left: auto; margin-right: auto">{{answer.author}}</div>
            </div>
            <div class="col-xs-10 question_intro">
                <div style="color:black; padding-right: 10px">{{answer.ans_content}}</div>
            </div>
          </div>

          <div class="question_card clearfix">
            <div class="agreebutton"><button type="button" class="btn btn-default" id="agree_button">赞 同 {{vote_num}}</button></div>
            

            <div class="date" style="float: right; margin-top: 10px; margin-right: 10px;">
                {{answer.ans_time|date:"Y-m-d"}}
            </div>
          </div>
        </div>

        <div style="margin-top: 10px;" class="clearfix">
            <form method="POST">
              {% csrf_token %}
              <textarea name="pinglun" id="pinglunkuang" cols="90" rows="3" placeholder="请输入你的评论" style="resize:none; margin-left: 5px;"></textarea>
              <button type="submit" class="btn btn-success" id="sub_btn" style="margin-top:5px; margin-right:10px; float: right;">提 交</button>
            </form>
        </div>

        <div class="comment_container">
            <div class="comment_card">
                <div style="font-weight:bold; font-size: 20px; border-bottom:1px solid black; margin-left: 10px;">
                    <i class="fa fa-comments" aria-hidden="true"></i>
                    评论 {{comment_num}}条
                </div>
                {% for comment in comments %}
                <div class="comment" style="position: relative">
                    <div class="col-xs-1"><i class="fa fa-user fa-3x" aria-hidden="true"></i></div>
                    <div class="col-xs-11">
                        <div style="font-weight: bold;">{{comment.commenter}}</div>
                        <div>{{comment.comment_content}}</div>
                        <div style="position: absolute; left: 13px; font-size: 10px; color: #999999">
                            {{comment.comment_time}}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
      </div>
      


      {% comment %} 右侧面板 {% endcomment %}
      <div class="col-md-3 fixed_mianban">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title" style="font-weight: bold;">功能中心</h3>
          </div>
          <div class="panel-body">
            <a href="/{{user_id}}/ask/raise" id="tiwen">我要提问</a>
          </div>
        </div>

        <div style="height: 300px; margin-top: 20px;">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title" style="font-weight: bold;">推荐话题</h3>
            </div>
            <div class="panel-body">
              <a href="/index/?tag=shenghuo"><button class="btn btn-default">生活</button></a>
              <a href="/index/?tag=xuexi"><button class="btn btn-default">学习</button></a>
              <a href="/index/?tag=tucao"><button class="btn btn-default">吐槽</button></a>
              <a href="/index/?tag=xuanke"><button class="btn btn-default">选课</button></a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <input type="hidden" value="{{status}}" id="agree_status" />
{% endblock content %}  

{% block script %}
<script>

    var vote_num = {{vote_num}};

    $(function(){
        bind_button();
        if($("#agree_status").val() == "True"){
          $("#agree_button").attr("class", "btn btn-primary");
          $("#agree_button").text("已赞同 " + vote_num);
        }
        else{
          $("#agree_button").attr("class", "btn btn-default");
          $("#agree_button").text("赞 同 " + vote_num);
        }
    })

    function bind_button() {
        $("#agree_button").click(function(){
            if($("#agree_button").text()[0] == '赞'){
              $("#agree_button").attr("class", "btn btn-primary");
              vote_num = vote_num + 1
              $("#agree_button").text("已赞同 " + vote_num);
              $.ajax({
                  url: '/answer/agree/',
                  type: "post",
                  data: {
                      answer_id: {{answer.id}}
                  },
                  dataType: "JSON",
                  success: function (res) {
                      console.log(res);
                      //location.reload();
                  }
              })
            }
            else{
              $("#agree_button").attr("class", "btn default");
              vote_num = vote_num - 1;
              $("#agree_button").text("赞 同 " + vote_num);
              $.ajax({
                url: '/answer/agree/cancel/',
                type: "post",
                data: {
                    answer_id: {{answer.id}}
                },
                dataType: "JSON",
                success: function (res) {
                    console.log(res);
                    //location.reload();
                }
              })
            }
        })
    }
</script>
{% endblock script %}

大二小学期项目/BUAAzhihu/BUAAzhihu/app1/templates/ask_raise.html
{% extends 'daohanglan.html' %}

{% block title %}
提问
{% endblock title %}

{% block style %}
    .content_container{
        margin-left: auto;
        margin-right: auto;
        width: 500px;
    }
  
    .ask_button{
        margin-top:10px;
        margin-left: auto;
        margin-right: auto;
    }
{% endblock style %}

{% block content %}
<div class='content_container clearfix'>
    <form method='POST'>
        {% csrf_token %}
        {% for field in form %}
        <div style="margin-top: 20px; font-weight: bold">{{field.label}}:</div>
        {{field}}
        {% endfor %}
        <button type="submit" class="btn btn-success" style="float: right; margin-top: 20px; margin-right: 20px;">提交问题</button>
    </form>
</div>
{% endblock content %}

大二小学期项目/BUAAzhihu/BUAAzhihu/app1/templates/homepage.html
{% extends 'daohanglan.html' %}

{% block title %}
主页
{% endblock title %}


{% block style %}
.content_container{
  margin-left: auto;
  margin-right: auto;
  width: 1030px;
}

.fixed_mianban{
  position: fixed;
  right: 215px;
}

.question_card{
  background-color: white;
  width: 100%;
  height: 130px;
  padding-left: auto;
  padding-right: auto;
  margin-top: 0px;
  border-bottom: 1px solid #f0f2f7;
}
.question_card a{
  text-decoration: none;
}
.username{
  display: inline-block;
  margin-top: 10px;
  margin-left: 10px;
}
.title_color{
  color: black;
}
.question_title{
  font-size:18px;
  font-weight: 600;
  margin-top: 10px;
  padding: 10px 10px 5px 10px;
}

.question_card .question_title a:hover{
  color: #625199;
}

.date{
  display: inline-block;
}
.answer{
  font-size:15px;
  padding:  0px 10px;
}
.answer_color{
  color:black;
}
.question_card .answer a:hover{
  color: grey;
}

.product-buyer-name {
  overflow:hidden; 
  text-overflow:ellipsis;
  display:-webkit-box; 
  -webkit-box-orient:vertical;
  -webkit-line-clamp:2; 
}

.agreebutton{
  position: relative
  bottom: 5px;
  margin-top:5px;
  padding-left: 10px;
  display: inline-block;
}

.col-md-3 a{
  text-decoration: none;
  font-size: 25px; 
  color: #238E68; 
  font-weight: bold
}

#tiwen:hover{
  color: #238000;
}

.col-md-3 button{
  background-color: #238E68;
  color: white;
  font-weight: bold;
}
  <!--下面是problem_page.py中的样式-->
{% endblock style %}


{% block content %}
  <div class="content_container">
    <div class="row">
      <div class="col-md-8" style="height: 1000px"> 
        
        <form method="get">
          <div class="btn-group btn-group-lg" role="group" style="margin-bottom:10px;">
            <button type="submit" class="btn btn-default" id="recommend" name="sort" value="rec">推荐</button>
            <button type="submit" class="btn btn-default" id="hot" name="sort" value="hot">热度</button>
            <button type="submit" class="btn btn-default" id="time" name="sort" value="time">时间</button>
          </div>
        </form>
        {% for answer in answers %}
          <div class="question_card" style="position: relative">
            <div class="question_title">
              <a href="/{{answer.thisask.id}}/problem" class="title_color">{{answer.thisask}}</a>
            </div>
            <div class="answer">
              <a href="/{{answer.thisask.id}}/problem/{{answer.id}}/answer" class="answer_color product-buyer-name">{{answer.author}}: {{answer.ans_content}}</a>
            </div>
            <div  style="position: absolute; bottom: 10px;" class="clearfix">
              <div class="agreebutton"><button type="button" class="btn btn-sm" id="{{answer.id}}" style="font-weight: bold">赞 同</button></div>
              <span style="margin-left: 30px;">
                <i class="fa fa-eye" aria-hidden="true"></i> 浏览量: {{answer.see_num}}
              </span>
              <span style="margin-left: 30px">
                <i class="fa fa-tag" aria-hidden="true"></i>{{answer.thisask.get_ask_kind_display}}
              </span>
              <div  style="display: inline-block; margin-left: 300px;">
                <i class="fa fa-calendar date" aria-hidden="true"></i>
                <div style="color:black;" class="date">{{answer.ans_time|date:"Y-m-d"}}</div>
              </div>
              
              
            </div>
            
          </div>
        {% endfor %}
        <ul class="pagination">
          {{ page_string }}
        </ul>
      </div>
      

      {% comment %} 右侧面板 {% endcomment %}
      <div class="col-md-3 fixed_mianban">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title" style="font-weight: bold;">功能中心</h3>
          </div>
          <div class="panel-body">
            <a href="/{{user_id}}/ask/raise" id="tiwen">我要提问</a>
          </div>
        </div>

        <div style="height: 300px; margin-top: 20px;">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title" style="font-weight: bold;">推荐话题</h3>
            </div>
            <form method='get'>
              <div class="panel-body">
                <button type="submit" class="btn btn-default" name="tag" value="shenghuo">生活</button>
                <button type="submit" class="btn btn-default" name="tag" value="xuexi">学习</button>
                <button type="submit" class="btn btn-default" name="tag" value="tucao">吐槽</button>
                <button type="submit" class="btn btn-default" name="tag" value="xuanke">选课</button>
              </div>
            </form>
            
          </div>
        </div>
      </div>

    </div>
  </div>

  <div id="agree_list">
    {% for status in agree_list %}
      <input type="hidden" value="{{status}}" />
    {% endfor %}
  </div>

  <div id="vote_num_list">
    {% for num in vote_ans_list %}
      <input type="hidden" value="{{num}}" />
    {% endfor %}
  </div>
{% endblock content %}  

{% block script %}
<script type="text/javascript">
  
  var cnt = 0;

  $(function () {
      var agree_list = [];
      len = $("#agree_list").children().length;
      for(var i = 0; i < len; i ++ )
      {
        if($("#agree_list").children()[i].value == 1){
          $($(".btn-sm")[i]).attr("class", "btn-primary btn-sm");
          $($(".btn-sm")[i]).text("已赞同 " + $("#vote_num_list").children()[i].value);
        }
        else{
          $($(".btn-sm")[i]).attr("class", "btn-default btn-sm");
          $($(".btn-sm")[i]).text("赞 同 " + $("#vote_num_list").children()[i].value);
        }
      }
      
      bind_button();

  });


  function bind_button() {
      var len = $(".btn-sm").length;
      //for(var i = 0; i < len; i ++ ){
      //  alert($(".btn-sm")[i].id);
      //}
      $(".btn-sm").click(function (){
        var str = $(this).text();
        var num = 0;
        for(var i = 0; i < str.length; i ++ ){
          if(str[i] >= '0' && str[i] <= '9')
          {
            var j = i;
            while(j < str.length && str[j] >= '0' && str[j] <= '9'){
              num = num * 10 + str[j] - '0';
              j ++ ;
            }
            i = j - 1;
          }
        }
        
        if($(this).text()[0] == "赞"){
          $(this).attr("class", "btn-primary btn-sm");
          $(this).text("已赞同 " + (num + 1));
          $.ajax({
            url: '/answer/agree/',
            type: "post",
            data: {
                answer_id: this.id
            },
            dataType: "JSON",
            success: function (res) {
                console.log(res);
            }
          })
        }
        else{
          $(this).attr("class", "btn-default btn-sm");
          $(this).text("赞 同 " + (num - 1));
          $.ajax({
            url: '/answer/agree/cancel/',
            type: "post",
            data: {
                answer_id: this.id
            },
            dataType: "JSON",
            success: function (res) {
                console.log(res);
            }
          })
        }
        
      })
    }
      /* $(".btn-sm").click(function () {
          $.ajax({
              url: '/index/agree/',
              type: "post",
              data: {
                  $
              },
              dataType: "JSON",
              success: function (res) {
                  console.log(res);
              }
          })
      })*/

</script>
{% endblock script %}

大二小学期项目/BUAAzhihu/BUAAzhihu/app1/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
    <style>

    </style>
</head>
<body>

    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.js' %}"></script>
    </body>
</html>